apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mirai-2026-prod

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

patches:
  - target:
      kind: Deployment
      name: mirai-bot
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 10
  
  - target:
      kind: Deployment
      name: ai-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3

patches:
  - target:
      kind: ConfigMap
      name: mirai-config
    patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: INFO
      - op: replace
        path: /data/SCANNER_MAX_CONNECTIONS
        value: "512"
      - op: replace
        path: /data/SCANNER_SCAN_RATE
        value: "5000"

resources:
  - hpa.yaml
