apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mirai-2026-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patches:
  - target:
      kind: Deployment
      name: mirai-bot
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  
  - target:
      kind: Deployment
      name: ai-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

patches:
  - target:
      kind: ConfigMap
      name: mirai-config
    patch: |-
      - op: replace
        path: /data/LOG_LEVEL
        value: DEBUG
      - op: replace
        path: /data/SCANNER_MAX_CONNECTIONS
        value: "64"
